### ISSUE TITLE
Applying scoped term codecs fails for redeclarations

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/cborld#2]
The algorithm for determining which codec to use when encoding/decoding a value is currently too simple and doesn't entirely take scoped terms into account. That is, when there is a redeclaration of an outer term, for example when `@protected` isn't used, last defined wins when it shouldn't.

The value encode/decode codec selection algorithm needs to be updated to take where the encoder/decoder is in the parsing tree into account as that can affect which codec is used for complex JSON-LD contexts.

**Comment by dlongley** [comment]
Fixed by #34.
