### ISSUE TITLE
Problems with lossless conversion of DateTime string using XsdDateTimeCodec

### ISSUE THREAD

**Issue by tplooker** [digitalbazaar/cborld#21]
It appears the [XsdDateTimeCodec](https://github.com/digitalbazaar/cborld/blob/main/lib/codecs/XsdDateTimeCodec.js) is encoding a valid date time string as Unix Epoch and then decoding it in accordance with [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601). However if the input string features only a Date component i.e '2021-02-22' upon encoding and then decoding the returned value becomes `2021-02-22T00:00:00Z` hence it is not lossless.

**Comment by dlongley** [comment]
Should be fixed by PR #34.
