### ISSUE TITLE
Convert 'cborld' library to isomorphic (to run in browser)

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/cborld#22]
Currently, this library is Node-only, but we need it to work in the browser (without Buffer polyfill and other stuff).

(Depends on PR https://github.com/digitalbazaar/cborld/pull/17).

We need to:

* [ ] Remove the Node-only fs caching [documentLoader](https://github.com/digitalbazaar/cborld/blob/main/lib/loader.js) (have it throw a 'Not Implemented' error just like the browser loader). This will remove the need for polyfills for `fs`, `os` and `path`.
* [ ] Convert all usages of Buffer to Uint8Array usages.
* [ ] (main blocker) Convert the `cbor` dependency to be isomorphic (to run the browser), currently it's Node-only.
    - the [`cbor-web` ](https://github.com/hildjj/node-cbor/tree/main/packages/cbor-web) variant uses Buffer polyfills; no good.
    - [`@ellipticoin/cbor`](https://github.com/ellipticoin/js-cbor) is isomorphic, but is way too basic (does not do what we need)

**Comment by dlongley** [comment]
Fixed by PR #34.
