### ISSUE TITLE
https://w3id.org/security/ed25519-signature-2018/v1 does not resolve

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/cborld#29]
please fix this immediately, before it starts to make everyone cry about JSON-LD :)

**Comment by OR13** [comment]
also `https://w3id.org/security/suites/x25519-2020/v1`... different URL format... pick a side of the road :)

**Comment by msporny** [comment]
`https://w3id.org/security/ed25519-signature-2018/v1` was done before we had finished arguing about what it should look like. I expect the proposed pattern going forward will be:

```
https://w3id.org/security/suites/ed25519-2018/v1
https://w3id.org/security/suites/x25519-2019/v1
https://w3id.org/security/suites/ed25519-2020/v1
https://w3id.org/security/suites/x25519-2020/v1
```

> pick a side of the road :)

pffft... roads... we don't /have/ roads out here...

<img src="https://media.giphy.com/media/XXo6LQ3Ujyy2s/giphy.gif">

**Comment by OR13** [comment]
I'm fine the `https://w3id.org/security/suites/ed25519-2020/v1` but it doesn't resolve either...

![anigif_original-4442-1456721306-9](https://user-images.githubusercontent.com/8295856/113490138-e187b900-948d-11eb-94cd-e87674a30197.gif)

**Comment by dmitrizagidulin** [comment]
@OR13 - Fixed; the following contexts resolve now:

* `https://w3id.org/security/suites/ed25519-2018/v1`
* `https://w3id.org/security/suites/ed25519-2020/v1`
* `https://w3id.org/security/suites/x25519-2020/v1`
