### ISSUE TITLE
appContextMap seems unused

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/cborld#30]
The activitystream example in the readme does not make use of appContextMap at all.

https://github.com/digitalbazaar/cborld#encode-to-cbor-ld

This feature seems like dangerous complexity, can it be safely removed?

**Comment by dlongley** [comment]
The `appContextMap` is for using contexts that are not in the registry. Also, this library is undergoing significant changes right now -- we'll see what shakes out.

**Comment by dlongley** [comment]
The `appContextMap` will be sticking around to enable unregistered contexts to be used but `appTermMap` has been removed as unnecessary at this time. Closing.
