### ISSUE TITLE
https://w3id.org/security/ed25519-signature-2020/v1 does not resolve

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/cborld#31]
same issue reported on https://github.com/digitalbazaar/cborld/issues/29

**Comment by dmitrizagidulin** [comment]
@OR13 - Fixed; the following contexts resolve now:

* `https://w3id.org/security/suites/ed25519-2018/v1`
* `https://w3id.org/security/suites/ed25519-2020/v1`
* `https://w3id.org/security/suites/x25519-2020/v1`
