### ISSUE TITLE
Add documentation for documentLoader

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/cborld#4]
@mattcollier wrote:
> The default documentLoader is used for CLI operations. documentLoader issues are very popular in jsonld related repos. Seems like a word or two about that would be good in the README.md.

**Comment by OR13** [comment]
Also, seems like `cborld.documentLoader` has a different signature than JSON-LD document loader...

`uri:string => Buffer<json(document)>` vs `uri:string => Buffer<json({contextUrl, documentUrl, document})>`

**Comment by dlongley** [comment]
Fixed by PR #34. `cborld.documentLoader` will be removed.
