### ISSUE TITLE
Unable to retrieve documentLoader

### ISSUE THREAD

**Issue by kezike** [digitalbazaar/cborld#52]
Are we supposed to provide our own document loader as an option input to `encode` and `decode`? [This line](https://github.com/digitalbazaar/cborld/blob/434c68a65de9e353601b1a404d6109a1285c498e/README.md?plain=1#L48) suggests that `documentLoader` is provided by this library, but this value appears to be undefined 🤔

**Comment by wip-abramson** [comment]
I also ran into this issue just now

**Comment by dlongley** [comment]
I pushed a quick update to the README to remove the `documentLoader` import and a comment in the example to mention the user must provide it. We need additional README updates for the new API features and I've filed #92 for that. Closing this issue based on these changes.
