### ISSUE TITLE
Encoded byte array prefix does not match the specification

### ISSUE THREAD

**Issue by filip26** [digitalbazaar/cborld#59]
Hi,
the first three bytes generated by the library are `0xd90501` for compressed output, but the specification defines `0xd95001` see [Compressed CBOR-LD Buffer Algorithm](https://digitalbazaar.github.io/cbor-ld-spec/#compressed-cbor-ld-buffer-algorithm)

**Comment by dlongley** [comment]
Relevant source line: https://github.com/digitalbazaar/cborld/blob/main/lib/encode.js#L38-L40

Which is correct ... the spec or the source?

**Comment by dlongley** [comment]
This was fixed in the spec. Thanks!
